apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  APP_ENV: "production"
  API_URL: "http://sample-app-service.default.svc.cluster.local"
  METRICS_ENABLED: "true" 